language: node_js
node_js:
  - "stable"
env:
  global:
    - TWILIO_ACCOUNT_SID=ACXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_API_KEY=SKXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    - TWILIO_API_SECRET=1CXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
